--TABLA ROJA=USUARIOS--

CREATE TABLE TIPOSUSUARIO (
IDTIPOUSUARIO INTEGER NOT NULL, 
NOMBRE VARCHAR2(80) NOT NULL, 
ESTATUS CHAR NOT NULL, 
CONSTRAINT TIPOSUSUARIO_PK PRIMARY KEY (IDTIPOUSUARIO)
);
   
CREATE TABLE USUARIOS (
NOMBRE VARCHAR2(30) NOT NULL, 
CONTRASENIA VARCHAR2(20) NOT NULL, 
ESTATUS CHAR NOT NULL, 
IDEMPLEADO INTEGER NOT NULL, 
IDTIPOUSUARIO INTEGER NOT NULL, 
CONSTRAINT USUARIOS_PK PRIMARY KEY (NOMBRE), 
CONSTRAINT FK_IDEMPLEADO FOREIGN KEY (IDEMPLEADO)
REFERENCES EMPLEADOS (IDEMPLEADO), 
CONSTRAINT FK_IDTIPOUSUARIO FOREIGN KEY (IDTIPOUSUARIO)
REFERENCES TIPOSUSUARIO (IDTIPOUSUARIO)
);

--TABLA AZUL=VENTAS--
create table UnidadesTransporte
(
  IdUnidadTransporte integer not null,
  Placas varchar2(10) not null,
  Marca varchar2(80) not null,
  Modelo varchar2(80) not null,
  Anio integer not null,
  Capacidad integer not null,
  constraint UnidadesTransporte_PK primary key(IdUnidadTransporte)
);

create table Cultivos
(
IdCultivo integer not null,
Nombre varchar2(100) not null,
CostoAsesoria float not null,
Estatus char not null,
constraint Cultivos_PK primary key(IdCultivo)
);

create table Asociaciones
(
IdAsociacion integer not null,
Nombre varchar2(100) not null,
Estatus char not null,
constraint Asociaciones_PK primary key(IdAsociacion)
);


CREATE TABLE CLIENTES (
IDCLIENTE NOT NULL, 
NOMBRE VARCHAR2(100) NOT NULL, 
RAZONSOCIAL VARCHAR2(100) NOT NULL, 
LIMITECREDITO FLOAT NOT NULL, 
DIRECCION VARCHAR2(80) NOT NULL, 
CODIGOPOSTAL CHAR NOT NULL, 
RFC CHAR NOT NULL, 
TELEFONO CHAR NOT NULL, 
EMAIL VARCHAR2(100) NOT NULL, 
TIPO CHAR NOT NULL, 
IDCIUDAD INTEGER NOT NULL, 
CONSTRAINT CLIENTES_PK PRIMARY KEY (IDCLIENTE), 
CONSTRAINT FK_CIUDADES_IDCIUD FOREIGN KEY (IDCIUDAD)
REFERENCES CIUDADES (IDCIUDAD)
);

CREATE TABLE MANTENIMIENTOS(
IDMANTENIMIENTO INTEGER NOT NULL, 
FECHA DATE NOT NULL, 
TALLER VARCHAR2(100) NOT NULL, 
COSTO FLOAT NOT NULL, 
COMENTARIOS VARCHAR2(200) NOT NULL, 
TIPO VARCHAR2(30) NOT NULL, 
IDUNIDADTRANSPORTE INTEGER NOT NULL, 
CONSTRAINT MANTENIMIENTOS_PK PRIMARY KEY (IDMANTENIMIENTO), 
CONSTRAINT MANTENIMIENTOS_UNIDADETRANS_FK FOREIGN KEY (IDUNIDADTRANSPORTE)
REFERENCES UNIDADESTRANSPORTE (IDUNIDADTRANSPORTE)
);

CREATE TABLE OFERTAS (
IDOFERTA INTEGER NOT NULL, 
NOMBRE VARCHAR2(50) NOT NULL, 
DESCRIPCION VARCHAR2(100) NOT NULL, 
PORDESCUENTO FLOAT NOT NULL, 
FECHAINICIO DATE NOT NULL, 
FECHAFIN DATE NOT NULL, 
CANMINPRODUCTO INTEGER NOT NULL, 
ESTATUS CHAR NOT NULL, 
IDPRODUCTO INTEGER NOT NULL, 
CONSTRAINT OFERTAS_PK PRIMARY KEY (IDOFERTA), 
CONSTRAINT OFERTAS_IDPRODU_FK FOREIGN KEY (IDPRODUCTO)
REFERENCES PRODUCTOS (IDPRODUCTO) 
);

CREATE TABLE OFERTASASOCIACION(
IDASOCIACION INTEGER NOT NULL, 
IDOFERTA INTEGER NOT NULL, 
ESTATUS CHAR NOT NULL, 
CONSTRAINT OFERTASASOCIACION_PK PRIMARY KEY (IDASOCIACION, IDOFERTA), 
CONSTRAINT OFERTASASOCIACION_ASOCIA_FK FOREIGN KEY (IDASOCIACION)
REFERENCES ASOCIACIONES (IDASOCIACION) ENABLE, 
CONSTRAINT OFERTASASOCIACION_OFERTAS_FK FOREIGN KEY (IDOFERTA)
REFERENCES OFERTAS (IDOFERTA)
);

CREATE TABLE MIEMBROS (
IDCLIENTE INTEGER NOT NULL, 
IDASOCIACION INTEGER NOT NULL, 
ESTATUS CHAR NOT NULL, 
FECHAINCORPORACION DATE NOT NULL, 
CONSTRAINT MIEMBROS_PK PRIMARY KEY (IDCLIENTE, IDASOCIACION), 
CONSTRAINT MIEMBROS_ASOCIACIONES_FK FOREIGN KEY (IDASOCIACION)
REFERENCES ASOCIACIONES (IDASOCIACION), 
CONSTRAINT MIEMBROS_CLIENTES_FK FOREIGN KEY (IDCLIENTE)
REFERENCES CLIENTES (IDCLIENTE) 
);

CREATE TABLE VENTASDETALLE(
IDVENTADETALLE INTEGER NOT NULL, 
PRECIOVENTA FLOAT NOT NULL, 
CANTIDAD FLOAT NOT NULL, 
SUBTOTAL FLOAT NOT NULL, 
IDVENTA INTEGER NOT NULL, 
IDPRESENTACION INTEGER NOT NULL, 
CONSTRAINT VENTASDETALLE_PK PRIMARY KEY (IDVENTADETALLE), 
CONSTRAINT VENTASDETALLE_VENTAS_FK FOREIGN KEY (IDVENTA)
REFERENCES VENTAS (IDVENTA), 
CONSTRAINT VENTASDETALLE_PRESENTA_FK FOREIGN KEY (IDPRESENTACION)
REFERENCES PRESENTACIONESPRODUCTO (IDPRESENTACION)
);


  CREATE TABLE CLIENTESCULTIVOS(	
  IDCLIENTECULTIVO INTEGER NOT NULL, 
	EXTENSION FLOAT NOT NULL, 
	UBICACION VARCHAR2(100) NOT NULL, 
	IDCLIENTE INTEGER NOT NULL, 
	IDCULTIVO INTEGER NOT NULL, 
	IDCIUDAD INTEGER NOT NULL, 
  CONSTRAINT CLIENTESCULTIVOS_PK PRIMARY KEY (IDCLIENTECULTIVO), 
  CONSTRAINT CLIENTESCULTIVOS_CULTIVOS_FK FOREIGN KEY (IDCULTIVO)
  REFERENCES CULTIVOS (IDCULTIVO), 
  CONSTRAINT CLIENTESCULTIVOS_CLIENTES_FK FOREIGN KEY (IDCLIENTE)
  REFERENCES CLIENTES (IDCLIENTE), 
  CONSTRAINT CLIENTESCULTIVOS_CIUDAD_FK FOREIGN KEY (IDCIUDAD)
  REFERENCES CIUDADES (IDCIUDAD)
  );

  
  CREATE TABLE VENTAS(	
  IDVENTA INTEGER NOT NULL, 
	FECHA DATE NOT NULL, 
	TOTALPAGAR FLOAT NOT NULL, 
	CANTPAGADA FLOAT NOT NULL, 
	COMENTARIOS VARCHAR2(100) NOT NULL, 
	ESTATUS CHAR NOT NULL, 
	TIPO CHAR NOT NULL, 
	IDCLIENTE INTEGER NOT NULL, 
	IDSUCURSAL INTEGER NOT NULL, 
	IDEMPLEADO INTEGER NOT NULL, 
  CONSTRAINT VENTAS_PK PRIMARY KEY (IDVENTA), 
  CONSTRAINT FK_IDCLIENTE FOREIGN KEY (IDCLIENTE)
  REFERENCES CLIENTES (IDCLIENTE), 
  CONSTRAINT FK_IDSUCURSAL FOREIGN KEY (IDSUCURSAL)
  REFERENCES SUCURSALES (IDSUCURSAL), 
  CONSTRAINT FK_VENTAS_IDEM FOREIGN KEY (IDEMPLEADO)
  REFERENCES EMPLEADOS ("IDEMPLEADO") 
  );
  
  
   
 CREATE TABLE FACTURAS(	
 FOLIO CHAR NOT NULL, 
 SUBTOTAL FLOAT NOT NULL, 
 IVA FLOAT NOT NULL, 
 NOMBREDOCXML VARCHAR2(100) NOT NULL, 
 DOCUMENTOXML BLOB NOT NULL, 
 NOMBRECOCPDF VARCHAR2(100) NOT NULL, 
 DOCUMENTOPDF BLOB NOT NULL, 
 IDVENTA INTEGER NOT NULL, 
 CONSTRAINT FACTURAS_PK PRIMARY KEY (FOLIO), 
 CONSTRAINT FACTURAS_VENTAS_FK1 FOREIGN KEY (IDVENTA)
 REFERENCES VENTAS (IDVENTA) 
);


 CREATE TABLE VISITAS(	
 IDVISITA INTEGER NOT NULL, 
 FECHAPLANEADA DATE NOT NULL, 
 FECHAREAL DATE NOT NULL, 
 COMENTARIOS VARCHAR2(200) NOT NULL, 
 ESTATUS CHAR NOT NULL, 
 COSTO FLOAT NOT NULL, 
 IDCLIENTECULTIVO INTEGER NOT NULL, 
 IDEMPLEADO INTEGER NOT NULL, 
 IDUNIDADTRANSPORTE INTEGER NOT NULL, 
 CONSTRAINT VISITAS_PK PRIMARY KEY (IDVISITA), 
 CONSTRAINT VISITAS_CLIENTESCULTIVOS_FK FOREIGN KEY (IDCLIENTECULTIVO)
 REFERENCES CLIENTESCULTIVOS (IDCLIENTECULTIVO), 
 CONSTRAINT VISITAS_UNIDADESTRANSPORTE_FK FOREIGN KEY (IDUNIDADTRANSPORTE)
 REFERENCES UNIDADESTRANSPORTE (IDUNIDADTRANSPORTE), 
 CONSTRAINT VISITAS_EMPLEADOS_FK FOREIGN KEY (IDEMPLEADO)
 REFERENCES EMPLEADOS (IDEMPLEADO)
);


 CREATE TABLE TRIPULACION(	
 IDEMPLEADO INTEGER NOT NULL, 
 IDENVIO INTEGER NOT NULL, 
 ROL VARCHAR2(50) NOT NULL, 
 CONSTRAINT TRIPULACION_PK PRIMARY KEY (IDEMPLEADO, IDENVIO, ROL), 
 CONSTRAINT TRIPULACION_ENVIOS_FK FOREIGN KEY (IDENVIO)
 REFERENCES ENVIOS (IDENVIO), 
 CONSTRAINT TRIPULACION_EMPLEADO_FK FOREIGN KEY (IDEMPLEADO)
	  REFERENCES EMPLEADOS ("IDEMPLEADO")
);
   

  CREATE TABLE COBROS (	
  IDCOBRO INTEGER NOT NULL, 
	FECHA DATE NOT NULL, 
	IMPORTE FLOAT NOT NULL, 
	IDVENTA INTEGER NOT NULL ENABLE, 
	IDFORMAPAGO INTEGER NOT NULL, 
  CONSTRAINT COBROS_PK PRIMARY KEY (IDCOBRO), 
  CONSTRAINT COBROS_VENTAS_FK FOREIGN KEY (IDVENTA)
  REFERENCES VENTAS (IDVENTA), 
  CONSTRAINT COBROS_FORMAPA_FK FOREIGN KEY (IDFORMAPAGO)
  REFERENCES FORMASPAGO (IDFORMAPAGO) 
);


 CREATE TABLE ENVIOS(
 IDENVIO INTEGER NOT NULL, 
 FECHAENTREGAPLANEADA DATE NOT NULL, 
 FECHAENTREGAREAL DATE NOT NULL, 
 DIRECCION VARCHAR2(100) NOT NULL, 
 CODIGOPOSTAL VARCHAR2(5) NOT NULL, 
 IDVENTA INTEGER NOT NULL, 
 IDUNIDADTRANSPORTE INTEGER NOT NULL, 
 IDCIUDAD INTEGER NOT NULL, 
 CONSTRAINT ENVIOS_PK PRIMARY KEY (IDENVIO), 
 CONSTRAINT ENVIOS_UNIDADTRANSPORTE_FK FOREIGN KEY (IDUNIDADTRANSPORTE)
 REFERENCES UNIDADESTRANSPORTE (IDUNIDADTRANSPORTE), 
 CONSTRAINT ENVIOS_VENTAS_FK FOREIGN KEY (IDVENTA)
 REFERENCES VENTAS (IDVENTA), 
 CONSTRAINT ENVIOS_CIUDAD_FK FOREIGN KEY (IDCIUDAD)
 REFERENCES CIUDADES (IDCIUDAD) 
);


---TABLA VERDE=COMPRAS--

 CREATE TABLE LABORATORIOS(
 IDLABORATORIO INTEGER NOT NULL, 
 NOMBRE VARCHAR2(50) NOT NULL, 
 ORIGEN VARCHAR2(30) NOT NULL, 
 ESTATUS CHAR NOT NULL, 
 CONSTRAINT "LABORATORIOS_PK" PRIMARY KEY ("IDLABORATORIO")
);


 CREATE TABLE CATEGORIAS(
 IDCATEGORIA INTEGER NOT NULL, 
 NOMBRE VARCHAR2(30) NOT NULL, 
 ESTATUS CHAR NOT NULL ENABLE, 
 CONSTRAINT CATEGORIAS_PK PRIMARY KEY (IDCATEGORIA)
 );
 
  CREATE TABLE UNIDADMEDIA(	
  IDUNIDAD INTEGER NOT NULL, 
	NOMBRE VARCHAR2(80) NOT NULL, 
	SIGLAS VARCHAR2(20) NOT NULL, 
	ESTATUS CHAR NOT NULL, 
  CONSTRAINT UNIDADMEDIA_PK PRIMARY KEY (IDUNIDAD)
);

 
 CREATE TABLE EMPAQUES(	
 IDEMPAQUE INTEGER NOT NULL, 
 NOMBRE VARCHAR2(80) NOT NULL, 
 CAPACIDAD FLOAT NOT NULL, 
 ESTATUS CHAR NOT NULL, 
 IDUNIDAD INTEGER NOT NULL, 
 CONSTRAINT "EMPAQUES_PK" PRIMARY KEY ("IDEMPAQUE"), 
 CONSTRAINT EMPAQUES_IDUNIDAD_FK FOREIGN KEY (IDUNIDAD)
 REFERENCES UNIDADMEDIA (IDUNIDAD)
);
 
 CREATE TABLE PRODUCTOS(	
 IDPRODUCTO INTEGER NOT NULL, 
 NOMBRE VARCHAR2(50) NOT NULL, 
 DESCRIPCION VARCHAR2(100) NOT NULL, 
 PUNTOREORDEN INTEGER NOT NULL, 
 PRECIOCOMPRA FLOAT NOT NULL, 
 PRECIOVENTA FLOAT NOT NULL, 
 INGREDIENTEACTIVO VARCHAR2(100) NOT NULL, 
 BANDATOXICOLOGICA VARCHAR2(80) NOT NULL, 
 APLICACION  VARCHAR2(200) NOT NULL, 
 USO VARCHAR2(200) NOT NULL, 
 ESTATUS  CHAR NOT NULL, 
 IDLABORATORIO INTEGER NOT NULL, 
 IDCATEGORIA INTEGER NOT NULL, 
 CONSTRAINT PRODUCTOS_PK PRIMARY KEY (IDPRODUCTO), 
 CONSTRAINT PRODUCTOS_IDCATEGORIA_FK FOREIGN KEY (IDCATEGORIA)
 REFERENCES CATEGORIAS (IDCATEGORIA), 
 CONSTRAINT PRODUCTOS_IDLABORATORIOS_FK FOREIGN KEY (IDLABORATORIO)
 REFERENCES LABORATORIOS (IDLABORATORIO) 
);


 CREATE TABLE PRESENTACIONESPRODUCTO(	
 IDPRESENTACION INTEGER NOT NULL, 
 PRECIOCOMPRA FLOAT NOT NULL, 
 PRECIOVENTA FLOAT NOT NULL, 
 PUNTOREORDEN FLOAT NOT NULL, 
 IDPRODUCTO INTEGER NOT NULL, 
 IDEMPAQUE INTEGER NOT NULL, 
 CONSTRAINT PRESENTACIONESPRODUCTO_PK PRIMARY KEY (IDPRESENTACION), 
 CONSTRAINT PRESENTACIONESPRODUCTO_IDEM_FK FOREIGN KEY (IDEMPAQUE)
 REFERENCES EMPAQUES (IDEMPAQUE), 
 CONSTRAINT PRESENTACIONESPRODU_IDPRO_FK FOREIGN KEY (IDPRODUCTO)
 REFERENCES PRODUCTOS (IDPRODUCTO) 
);


 CREATE TABLE SUCURSALES(	
 IDSUCURSAL INTEGER NOT NULL, 
 NOMBRE VARCHAR2(50) NOT NULL, 
 TELEFONO VARCHAR2(15) NOT NULL, 
 DIRECCION VARCHAR2(80) NOT NULL, 
 COLONIA VARCHAR2(50) NOT NULL, 
 CODIGOPOSTAL VARCHAR2(5) NOT NULL, 
 PRESUPUESTO FLOAT NOT NULL, 
 ESTATUS CHAR NOT NULL, 
 IDCIUDAD INTEGER NOT NULL, 
 CONSTRAINT SUCURSALES_PK PRIMARY KEY (IDSUCURSAL), 
 CONSTRAINT SUCURSALES_IDCIUDAD_FK FOREIGN KEY (IDCIUDAD)
	  REFERENCES CIUDADES (IDCIUDAD) 
);

 CREATE TABLE EXISTENCIASSUCURSAL(
 IDPRESENTACION INTEGER NOT NULL, 
 IDSUCURSAL INTEGER NOT NULL, 
 CANTIDAD FLOAT NOT NULL, 
 CONSTRAINT EXISTENCIASSUCURSAL_PK PRIMARY KEY (IDPRESENTACION, IDSUCURSAL), 
 CONSTRAINT EXISTENCIASSUCURSAL_IDPRE_FK FOREIGN KEY (IDPRESENTACION)
 REFERENCES PRESENTACIONESPRODUCTO (IDPRESENTACION), 
 CONSTRAINT EXISTENCIASSUCURSAL_IDSUCU_FK FOREIGN KEY (IDSUCURSAL)
 REFERENCES SUCURSALES (IDSUCURSAL)
);


 CREATE TABLE IMAGENESPRODUCTO(	
 IDIMAGEN INTEGER NOT NULL, 
 NOMBREIMAGEN VARCHAR2(100) NOT NULL, 
 IMAGEN BLOB NOT NULL, 
 PRINCIPAL CHAR NOT NULL, 
 IDPRODUCTO INTEGER NOT NULL, 
 CONSTRAINT IMAGENESPRODUCTO_PK PRIMARY KEY (IDIMAGEN), 
 CONSTRAINT IMAGENESPRODUCTO_IDPRODU_FK FOREIGN KEY (IDPRODUCTO)
 REFERENCES PRODUCTOS (IDPRODUCTO) 
); 


 CREATE TABLE PROVEEDORES(	
 IDPROVEEDOR INTEGER NOT NULL, 
 NOMBRE VARCHAR2(80) NOT NULL, 
 TELEFONO CHAR NOT NULL, 
 EMAIL VARCHAR2(100) NOT NULL, 
 DIRECCION VARCHAR2(80) NOT NULL, 
 COLONIA VARCHAR2(50) NOT NULL, 
 CODIGOPOSTAL VARCHAR2(5) NOT NULL ENABLE, 
 IDCIUDAD INTEGER NOT NULL, 
 CONSTRAINT PROVEEDORES_PK PRIMARY KEY (IDPROVEEDOR), 
 CONSTRAINT PROVEEDORES_IDCIUDAD_FK FOREIGN KEY (IDCIUDAD)
 REFERENCES CIUDADES (IDCIUDAD) 
 );



 
 CREATE TABLE PRODUCTOSPROVEEDOR(	
 IDPROVEEDOR INTEGER NOT NULL, 
 IDPRESENTACION INTEGER NOT NULL, 
 DIASRETARDO INTEGER NOT NULL, 
 PRECIOESTANDAR FLOAT NOT NULL, 
 PRECIOULTIMACOMPRA FLOAT NOT NULL, 
 CANTMINPERDIR INTEGER NOT NULL, 
 CANTMAXPEDIR INTEGER NOT NULL, 
 CONSTRAINT PRODUCTOSPROVEEDOR_PK PRIMARY KEY (IDPROVEEDOR, IDPRESENTACION), 
 CONSTRAINT PRODUCTOSPROVEEDOR_IDPRESEN_FK FOREIGN KEY (IDPRESENTACION)
 REFERENCES PRESENTACIONESPRODUCTO (IDPRESENTACION), 
 CONSTRAINT PRODUCTOSPROVEEDOR_IDPROVE_FK FOREIGN KEY (IDPROVEEDOR)
 REFERENCES PROVEEDORES (IDPROVEEDOR) 
);


 CREATE TABLE PEDIDOS(
 IDPEDIDO INTEGER NOT NULL, 
 FECHAREGISTRO DATE NOT NULL, 
 FECHARECEPCION DATE NOT NULL, 
 TOTALPAGAR FLOAT NOT NULL, 
 CANTIDADPAGADA FLOAT NOT NULL, 
 ESTATUS CHAR NOT NULL, 
 IDPROVEEDOR INTEGER NOT NULL, 
 IDSUCURSAL INTEGER NOT NULL, 
 IDEMPLEADO INTEGER NOT NULL, 
 CONSTRAINT PEDIDOS_PK PRIMARY KEY (IDPEDIDO), 
 CONSTRAINT PEDIDOS_IDEMPLEADO_FK FOREIGN KEY (IDEMPLEADO)
 REFERENCES EMPLEADOS (IDEMPLEADO), 
	 CONSTRAINT PEDIDOS_IDPROVEEDOR_FK FOREIGN KEY (IDPROVEEDOR)
	  REFERENCES PROVEEDORES (IDPROVEEDOR), 
	 CONSTRAINT PEDIDOS_IDSUCURSAL_FK FOREIGN KEY (IDSUCURSAL)
	  REFERENCES SUCURSALES (IDSUCURSAL)
);


CREATE TABLE PEDIDODETALLE(	
IDPEDIDODETALLE INTEGER NOT NULL, 
CANTPEDIDA INTEGER NOT NULL, 
PRECIOCOMPRA FLOAT NOT NULL, 
SUBOTAL FLOAT NOT NULL, 
CANTRECIBIDA INTEGER NOT NULL, 
CANTRECHAZADA INTEGER NOT NULL, 
CANTACEPTADA FLOAT NOT NULL, 
IDPEDIDO INTEGER NOT NULL, 
IDPRESENTACION INTEGER NOT NULL, 
CONSTRAINT PEDIDODETALLE_PK PRIMARY KEY (IDPEDIDODETALLE), 
CONSTRAINT PEDIDODETALLE_IDPEDIDO_FK FOREIGN KEY (IDPEDIDO)
REFERENCES PEDIDOS (IDPEDIDO), 
CONSTRAINT PEDIDODETALLE_IDPRESENTA_FK FOREIGN KEY (IDPRESENTACION)
REFERENCES PRESENTACIONESPRODUCTO (IDPRESENTACION) 
);



 CREATE TABLE CONTACTOSPROVEEDOR(	
 IDCONTACTO INTEGER NOT NULL, 
 NOMBRE VARCHAR2(80) NOT NULL, 
 TELEFONO CHAR NOT NULL, 
 EMAIL VARCHAR2(100) NOT NULL, 
 IDPROVEEDOR INTEGER NOT NULL, 
 CONSTRAINT CONTACTOSPROVEEDOR_PK PRIMARY KEY (IDCONTACTO), 
 CONSTRAINT CONTACTOSPROVEEDOR_IDPROVE_FK FOREIGN KEY (IDPROVEEDOR)
	  REFERENCES PROVEEDORES (IDPROVEEDOR) 
);


 CREATE TABLE CUENTASPROVEEDOR(
 IDCUENTAPROVEEDOR INTEGER NOT NULL, 
 IDPROVEEDOR INTEGER NOT NULL, 
 NOCUENTA VARCHAR2(10) NOT NULL, 
 BANCO VARCHAR2(30) NOT NULL, 
 CONSTRAINT CUENTASPROVEEDOR_PK PRIMARY KEY (IDCUENTAPROVEEDOR), 
 CONSTRAINT CUENTASPROVEEDOR_IDPRO_FK FOREIGN KEY (IDPROVEEDOR)
 REFERENCES PROVEEDORES (IDPROVEEDOR) 
);



  CREATE TABLE PAGOS(	
  IDPAGO INTEGER NOT NULL, 
  FECHA DATE NOT NULL, 
	IMPORTE FLOAT NOT NULL, 
	IDPEDIDO INTEGER NOT NULL, 
  IDFORMAPAGO INTEGER NOT NULL, 
	IDCUENTAPROVEEDOR INTEGER NOT NULL, 
  CONSTRAINT PAGOS_PK PRIMARY KEY (IDPAGO), 
  CONSTRAINT PAGOS_IDCUENTAPRO_FK FOREIGN KEY (IDCUENTAPROVEEDOR)
  REFERENCES CUENTASPROVEEDOR (IDCUENTAPROVEEDOR), 
  CONSTRAINT PAGOS_IDFORMAPAGO_FK FOREIGN KEY (IDFORMAPAGO)
  REFERENCES FORMASPAGO (IDFORMAPAGO), 
  CONSTRAINT PAGOS_IDPEDIDO_FK FOREIGN KEY (IDPEDIDO)
	  REFERENCES PEDIDOS (IDPEDIDO) 
   );


---TABLA AMARILLA=RECURSOS HUMANOS---


  CREATE TABLE ESTADOS(	
  IDESTADO INTEGER NOT NULL, 
	NOMBRE VARCHAR2(60) NOT NULL, 
	SIGLAS VARCHAR2(10) NOT NULL, 
	ESTATUS CHAR NOT NULL, 
  CONSTRAINT ESTADOS_PK PRIMARY KEY (IDESTADO)
  );
  
   CREATE TABLE DEPARTAMENTOS(	
   IDDEPARTAMENTO INTEGER NOT NULL, 
	 NOMBRE VARCHAR2(50) NOT NULL, 
	 ESTATUS CHAR NOT NULL, 
	 CONSTRAINT DEPARTAMENTOS_PK PRIMARY KEY (IDDEPARTAMENTO)
   );
  
  
   CREATE TABLE DEDUCCIONES(	
   IDDEDUCCION INTEGER NOT NULL, 
	 NOMBRE VARCHAR2(30) NOT NULL, 
   DESCRIPCION VARCHAR2(80) NOT NULL, 
	 PORCENTAJE FLOAT NOT NULL, 
	 CONSTRAINT DEDUCCIONES_PK PRIMARY KEY (IDDEDUCCION)
   );


 CREATE TABLE PERCEPCIONES(	
 IDPERCEPCION INTEGER NOT NULL, 
 NOMBRE VARCHAR2(30) NOT NULL, 
 DESCRIPCION VARCHAR2(80) NOT NULL, 
 DIASPAGAR INTEGER NOT NULL, 
 CONSTRAINT PERCEPCIONES_PK PRIMARY KEY (IDPERCEPCION)
 );
 
 
  CREATE TABLE PUESTOS(	
  IDPUESTO INTEGER NOT NULL, 
  NOMBRE VARCHAR2(60) NOT NULL, 
  SALARIOMINIMO FLOAT NOT NULL, 
  SALARIOMAXIMO FLOAT NOT NULL, 
	ESTATUS CHAR NOT NULL, 
  CONSTRAINT PUESTOS_PK PRIMARY KEY (IDPUESTO)
   );


 CREATE TABLE FORMASPAGO(	
 IDFORMAPAGO INTGER NOT NULL, 
 NOMBRE VARCHAR2(50) NOT NULL, 
 ESTATUS CHAR NOT NULL, 
 CONSTRAINT FORMASPAGO_PK PRIMARY KEY (IDFORMAPAGO)
 );



CREATE TABLE INCAPACIDADES(	
IDINCAPACIDAD INTEGER NOT NULL, 
FECHAINICIO DATE NOT NULL, 
FECHAFIN DATE NOT NULL, 
ENFERMEDAD VARCHAR2(150) NOT NULL, 
EVIDENCIA BLOB NOT NULL, 
IDEMPLEADO INTEGER NOT NULL, 
CONSTRAINT INCAPACIDADES_PK PRIMARY KEY (IDINCAPACIDAD), 
CONSTRAINT INCAPACIDADES_IDEMPLEADO_FK FOREIGN KEY (IDEMPLEADO)
REFERENCES EMPLEADOS (IDEMPLEADO) 
);


 CREATE TABLE CIUDADES(	
 IDCIUDAD INTEGER NOT NULL, 
 NOMBRE VARCHAR2(80) NOT NULL, 
 IDESTADO INTEGER NOT NULL, 
 ESTATUS CHAR NOT NULL, 
 CONSTRAINT CIUDADES_PK PRIMARY KEY (IDCIUDAD), 
 CONSTRAINT FK_IDESTADO FOREIGN KEY (IDESTADO)
 REFERENCES ESTADOS (IDESTADO) 
  );



 CREATE TABLE EMPLEADOS(	
 IDEMPLEADO INTEGER  NOT NULL, 
 NOMBRE VARCHAR2(30) NOT NULL, 
 APATERNO VARCHAR2(30) NOT NULL, 
 AMATERNO VARCHAR2(30) NOT NULL, 
 SEXO CHAR NOT NULL, 
 FECHACONTRATACION DATE NOT NULL, 
 FECHANACIMIENTO DATE NOT NULL, 
 SALARIO FLOAT NOT NULL, 
 NSS VARCHAR2(10) NOT NULL, 
 ESTADOCIVIL VARCHAR2(20) NOT NULL, 
 DIASVACACIONES INTEGER NOT NULL, 
 DIASPERMISO INTEGER NOT NULL, 
 FOTOGRAFIA BLOB NOT NULL, 
 DIRECCION VARCHAR2(80) NOT NULL, 
 COLONIA VARCHAR2(50) NOT NULL, 
 CODIGOPOSTAL VARCHAR2(5) NOT NULL, 
 ESCOLARIDAD VARCHAR2(80) NOT NULL, 
 PORCENTAJECOMISION FLOAT NOT NULL, 
 ESTATUS CHAR NOT NULL, 
 IDDEPARTAMENTO INTEGER NOT NULL, 
 IDPUESTO INTEGER NOT NULL, 
 IDCIUDAD INTEGER NOT NULL, 
 IDSUCURSAL INTEGER NOT NULL, 
 CONSTRAINT EMPLEADOS_PK PRIMARY KEY (IDEMPLEADO), 
 CONSTRAINT EMPLEADOS_IDCIUDAD_FK FOREIGN KEY (IDCIUDAD)
 REFERENCES CIUDADES (IDCIUDAD), 
 CONSTRAINT EMPLEADOS_IDDEPARTAMENTO_FK FOREIGN KEY (IDDEPARTAMENTO)
 REFERENCES DEPARTAMENTOS (IDDEPARTAMENTO), 
 CONSTRAINT EMPLEADOS_IDPUESTO_FK FOREIGN KEY (IDPUESTO)
 REFERENCES PUESTOS (IDPUESTO), 
 CONSTRAINT EMPLEADOS_IDSUCURSAL_FK FOREIGN KEY (IDSUCURSAL)
	  REFERENCES SUCURSALES (IDSUCURSAL) 
);


 CREATE TABLE HORARIOS(	
 IDHORARIO INTEGER NOT NULL, 
 HORAINICIO DATE NOT NULL, 
 HORAFIN DATE NOT NULL, 
 DIAS VARCHAR2(30) NOT NULL, 
 IDEMPLEADO INTEGER NOT NULL, 
 CONSTRAINT HORARIOS_PK PRIMARY KEY (IDHORARIO), 
 CONSTRAINT HORARIOS_IDEMPLEADOS_FK FOREIGN KEY (IDEMPLEADO)
 REFERENCES EMPLEADOS (IDEMPLEADO) 
  );
  
  
  
   CREATE TABLE AUSENCIASJUSTIFICADAS(	
   IDAUSENCIA INTEGER NOT NULL, 
   FECHASOLICITUD DATE NOT NULL, 
	 FECHAINICIO DATE NOT NULL, 
	 FECHAFIN DATE NOT NULL, 
	 TIPO CHAR NOT NULL, 
	 IDEMPLEADOS INTEGER NOT NULL, 
   IDEMPLEADOA INTEGER NOT NULL, 
	 CONSTRAINT AUSENCIASJUSTIFICADAS_PK PRIMARY KEY (IDAUSENCIA), 
	 CONSTRAINT FK_IDEMPLEADOS FOREIGN KEY (IDEMPLEADOS)
   REFERENCES EMPLEADOS" (IDEMPLEADO), 
	 CONSTRAINT FK_IDEMPLEADOA FOREIGN KEY (IDEMPLEADOA)
	  REFERENCES EMPLEADOS (IDEMPLEADO) 
   );

  

 CREATE TABLE HISTORIALPUESTOS(	
 IDEMPLEADO INTEGER NOT NULL, 
 IDPUESTO INTEGER NOT NULL, 
 IDDEPARTAMENTO INTEGER NOT NULL, 
 FECHAINICIO DATE NOT NULL, 
 FECHAFIN DATE NOT NULL, 
 SALARIO FLOAT NOT NULL, 
 CONSTRAINT HISTORIALPUESTOS_PK PRIMARY KEY (IDEMPLEADO, IDPUESTO, IDDEPARTAMENTO, FECHAINICIO), 
 CONSTRAINT HISTORIALPUESTOS_IDDEPART_FK FOREIGN KEY (IDDEPARTAMENTO)
 REFERENCES DEPARTAMENTOS (IDDEPARTAMENTO), 
 CONSTRAINT HISTORIALPUESTOS_IDEMPLEADO_FK FOREIGN KEY (IDEMPLEADO)
 REFERENCES EMPLEADOS (IDEMPLEADO), 
 CONSTRAINT HISTORIALPUESTOS_IDPUESTOS_FK FOREIGN KEY (IDPUESTO)
 REFERENCES PUESTOS (IDPUESTO) 
 );



 CREATE TABLE DOCUMENTACIONEMPLEADO(	
 IDDOCUMENTO INTEGER NOT NULL, 
 NOMBREDOCUMENTO VARCHAR2(80) NOT NULL, 
 FECHAENTREGA DATE NOT NULL, 
 DOCUMENTO BLOB NOT NULL, 
 IDEMPLEADO INTEGER NOT NULL, 
 CONSTRAINT DOCUMENTACIONEMPLEADO_PK PRIMARY KEY (IDDOCUMENTO), 
 CONSTRAINT DOCUMENTACIONEMPLEADO_IDEMP_FK FOREIGN KEY (IDEMPLEADO)
 REFERENCES EMPLEADOS (IDEMPLEADO)
);



 CREATE TABLE NOMINAS(	
 IDNOMINA INTEGER NOT NULL, 
 FECHAPAGO DATE NOT NULL, 
 TOTALIP FLOAT NOT NULL, 
 TOTALID FLOAT NOT NULL, 
 CANTIDADNETA FLOAT NOT NULL, 
 DIASTRAJADOS INTEGER NOT NULL, 
 FALTAS INTEGER NOT NULL, 
 FECHAINICIO DATE NOT NULL, 
 FECHAFIN DATE NOT NULL, 
 IDEMPLEADO INTEGER NOT NULL, 
 IDFORMAPAGO INTEGER NOT NULL, 
 CONSTRAINT NOMINAS_PK PRIMARY KEY (IDNOMINA), 
 CONSTRAINT NOMINAS_IDEMPLEADO_FK FOREIGN KEY (IDEMPLEADO)
 REFERENCES EMPLEADOS (IDEMPLEADO), 
 CONSTRAINT NOMINAS_IDFORMAPAGO_FK FOREIGN KEY (IDFORMAPAGO)
 REFERENCES FORMASPAGO (IDFORMAPAGO) 
  );



 CREATE TABLE NOMINASPERCEPCIONES(	
 IDNOMINA INTEGER NOT NULL, 
 IDPERCEPCION INTEGER NOT NULL, 
 IMPORTE FLOAT NOT NULL, 
 CONSTRAINT NOMINASPERCEPCIONES_PK PRIMARY KEY (IDNOMINA, IDPERCEPCION), 
 CONSTRAINT NOMINASPERCEPCIONES_IDNO_FK FOREIGN KEY (IDNOMINA)
 REFERENCES NOMINAS (IDNOMINA), 
 CONSTRAINT NOMINASPERCEPCIONES_IDPERCE_FK FOREIGN KEY (IDPERCEPCION)
 REFERENCES PERCEPCIONES (IDPERCEPCION) 
 );



 CREATE TABLE NOMINASDEDUCCIONES(	
 IDNOMINA INTEGER NOT NULL, 
 IDDEDUCCION INTEGER NOT NULL, 
 IMPORTE FLOAT NOT NULL, 
 CONSTRAINT NOMINASDEDUCCIONES_PK PRIMARY KEY (IDNOMINA, IDDEDUCCION), 
 CONSTRAINT NOMINASDEDUCCIONES_IDDEDUC_FK FOREIGN KEY (IDDEDUCCION)
 REFERENCES DEDUCCIONES (IDDEDUCCION), 
 CONSTRAINT NOMINASDEDUCCIONES_IDNOMINA_FK FOREIGN KEY (IDNOMINA)
 REFERENCES NOMINAS (IDNOMINA) 
);

